name = "BV"
version = "0.1.0"
defaultTargets = ["BV", "LargeSieve"]

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "BV"

[[lean_lib]]
name = "LargeSieve"

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "v4.28.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "leancert"
git = "https://github.com/alerad/leancert"
rev = "v4.28.1"

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"
rev = "11265859849c1b7029fa68dfb2e3822596c74c9d"


